### ISSUE TITLE
SyntaxError when importing Document and/or FileBackend

### ISSUE THREAD

**Issue by triitaoj** [adewes/blitzdb#57]
Is blitzdb compatible with older versions of python? RHEL6 still uses version 2.6.6.

I tried to do the imports shown in https://github.com/adewes/blitzdb#user-content-examples

```
$ pip show blitzdb
---
Metadata-Version: 1.0
Name: blitzdb
Version: 0.2.12
Summary: A document-oriented database written purely in Python.
Home-page: https://github.com/adewes/blitzdb
Author: Andreas Dewes - 7scientists
Author-email: andreas@7scientists.com
License: MIT
Location: /usr/lib/python2.6/site-packages
Requires:
```
```
$ python -V
Python 2.6.6
```
```
$ head -2 test_blitzdb.py
from blitzdb import Document
from blitzdb import FileBackend
```
```
$ python test_blitzdb.py
Traceback (most recent call last):
  File "test_blitzdb.py", line 2, in <module>
    from blitzdb import Document
  File "/usr/lib/python2.6/site-packages/blitzdb/__init__.py", line 2, in <module>
    from .backends.file import Backend as FileBackend
  File "/usr/lib/python2.6/site-packages/blitzdb/backends/file/__init__.py", line 1, in <module>
    from blitzdb.backends.file.backend import Backend
  File "/usr/lib/python2.6/site-packages/blitzdb/backends/file/backend.py", line 13, in <module>
    from blitzdb.backends.file.index import (
  File "/usr/lib/python2.6/site-packages/blitzdb/backends/file/index.py", line 105
    self._undefined_keys = {key : True for key in undefined_values}
                                         ^
SyntaxError: invalid syntax
$
```

**Comment by orgkhnargh** [comment]
Python 2.6 does not support dict comprehensions. Blitzdb utilizes dict comprehensions, so it cannot be used with Python 2.6.
